# fly.toml app configuration file generated for aquasave-edgeapi on 2026-07-05T00:40:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aquasave-edgeapi'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  BACKEND_BASE_URL = 'https://aquasave-backend.onrender.com'
  COMMAND_POLL_INTERVAL_MS = '3000'
  MQTT_BROKER_URL = 'mqtts://109a1a97e0814454afa8d22b818e2da5.s1.eu.hivemq.cloud:8883'
  MQTT_CLIENT_ID = 'aquasave-edge-service'
  MQTT_USERNAME = 'aquasave-edge'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
